plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'greg'
version = '1.0'

repositories {
    mavenCentral()
}

application {
    // Note: ensure this matches your folder structure greg/Greg.java
    mainClass = 'greg.Greg'
}

shadowJar {
    archiveBaseName.set('greg')
    archiveClassifier.set('')
    archiveVersion.set('')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}